package com.cesarconstanzo.kanban_board_api.model;

import jakarta.persistence.*;
import lombok.*;

import java.util.List;

/**
 * Represents a Kanban Board.
 * A Board is the main container that holds multiple columns.
 */

@Entity // Marks this class as a JPA entity (table in the database)
@Table(name = "boards") // Defines the table name in the database
@Getter // Lombok: generates getters automatically
@Setter // Lombok: generates setters automatically
@NoArgsConstructor // Lombok: generates a no-args constructor
@AllArgsConstructor // Lombok: generates a constructor with all fields
@Builder // Lombok: enables builder pattern (Board.builder()...)

public class Board {
    /**
     * Primary key of the Board.
     * It is automatically generated by the database (auto-increment).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    /**
     * Name of the board.
     * Cannot be null (required field).
     */

    @Column(nullable = false)
    private String name;

    /**
     * Relationship: One Board has many Columns.
     * mappedBy = "board":
     * Indicates that the 'board' field in the Column class owns the relationship.
     * cascade = CascadeType.ALL:
     * All operations (save, delete, update) performed on Board
     * will also be applied to its Columns.
     * Example:
     * If you delete a Board, all associated Columns will also be deleted.
     */

    @OneToMany(mappedBy = "board", cascade = CascadeType.ALL)
    private List<BoardColumn> columns;
}
